// weeks/week3.js — Week 3: Five Senses + You Are My Sunshine
window.WEEK_DATA = {
  title: 'Five Senses',
  titleEmoji: '👁️',

  feelings: [
    { word: 'curious',   zh: '好奇的',   emoji: '🤔', color: '#74B9FF' },
    { word: 'loving',    zh: '充滿愛的', emoji: '🥰', color: '#FF85CA' },
    { word: 'peaceful',  zh: '平靜的',   emoji: '😌', color: '#81ECEC' },
    { word: 'amazed',    zh: '驚嘆的',   emoji: '🤩', color: '#FFD93D' },
    { word: 'disgusted', zh: '噁心的',   emoji: '🤢', color: '#55EFC4' },
    { word: 'jealous',   zh: '嫉妒的',   emoji: '😒', color: '#A29BFE' },
    { word: 'lonely',    zh: '孤單的',   emoji: '😔', color: '#B2BEC3' },
    { word: 'grateful',  zh: '感激的',   emoji: '🙏', color: '#FFEAA7' },
  ],

  sightWords: [
    // Five Senses vocabulary
    { word: 'see',    zh: '看見',   sentence: 'I see a beautiful flower.' },
    { word: 'hear',   zh: '聽見',   sentence: 'I hear the birds singing.' },
    { word: 'smell',  zh: '聞',     sentence: 'I smell the sweet cookies.' },
    { word: 'taste',  zh: '品嚐',   sentence: 'I taste the yummy fruit.' },
    { word: 'touch',  zh: '觸碰',   sentence: 'I touch the soft grass.' },
    { word: 'eyes',   zh: '眼睛',   sentence: 'I see with my eyes.' },
    { word: 'ears',   zh: '耳朵',   sentence: 'I hear with my ears.' },
    { word: 'nose',   zh: '鼻子',   sentence: 'I smell with my nose.' },
    { word: 'tongue', zh: '舌頭',   sentence: 'I taste with my tongue.' },
    { word: 'hands',  zh: '手',     sentence: 'I touch with my hands.' },
    { word: 'mouth',  zh: '嘴巴',   sentence: 'Open your mouth and taste it.' },
    { word: 'listen', zh: '聆聽',   sentence: 'Listen to the birds!' },
    { word: 'sight',  zh: '視覺',   sentence: 'What a beautiful sight!' },
    { word: 'fit',    zh: '合適',   sentence: 'We are all a good fit.' },
    { word: 'flew',   zh: '飛過',   sentence: 'The birds flew away.' },
    { word: 'flower', zh: '花',     sentence: 'The flower smells sweet.' },
    // f-words
    { word: 'fly',    zh: '飛',     sentence: 'Birds can fly high.' },
    { word: 'for',    zh: '為了',   sentence: 'This is for you.' },
    { word: 'four',   zh: '四',     sentence: 'I have four friends.' },
    { word: 'friend', zh: '朋友',   sentence: 'She is my best friend.' },
    { word: 'from',   zh: '從',     sentence: 'She came from far away.' },
    { word: 'funny',  zh: '有趣的', sentence: 'That bug looks funny!' },
  ],

  sightColors: ['#FF6B6B','#A29BFE','#FFD93D','#00B894','#FF85CA','#74B9FF','#E17055','#FD79A8','#00CEC9','#6C5CE7'],

  sentenceGroups: [
    { title: '📖 Special Friends', count: 20 },
    { title: '👁️ Helen\'s Walk', count: 15 },
    { title: '💬 Sentence Patterns', count: 5 },
    { title: '♫ You Are My Sunshine', count: 8 },
  ],

  sentences: [
    // Special Friends Sentences — Unit 3 (9)
    { en: 'Mum said I can have four friends over from school.', zh: '媽媽說過我可以從學校邀請四個小朋友來家裡玩。' },
    { en: 'I have great ideas to have lots of fun.', zh: '而我對此已經想好了很多好玩的點子。' },
    { en: 'Miles has a big kite that can fly high in the sky.', zh: 'Miles 有個風箏能在天空高高地飛。' },
    { en: 'And today I can hear the wind outside.', zh: '今天我剛好聽見外面風的聲音。' },
    { en: 'Listen to the wind howling.', zh: '聽著那呼嘯的風。' },
    { en: 'Perfect day for kite flying.', zh: '今天是最適合放風箏的一天了。' },
    { en: "Jess's grandma makes the best cookies.", zh: 'Jess 奶奶烤的餅乾是我吃過最棒的。' },
    { en: 'I can already smell the sweetness through my nose and my mouth is watering.', zh: '我已經能聞到餅乾的香甜氣味而開始流口水了。' },
    { en: 'Can you taste it?', zh: '你能感受到嗎？' },
    { en: 'Sam is very creative.', zh: 'Sam 很有創意。' },
    { en: 'He can make his own clay.', zh: '他會做黏土。' },
    { en: 'It feels all squishy when you touch it.', zh: '黏土摸起來濕濕軟軟的。' },
    { en: 'I love getting my hands dirty.', zh: '我喜歡把手用的髒髒的。' },
    { en: 'If you touch the clay, it starts to sparkle and we can see all the glitter.', zh: '如果你多捏黏土，隨著不同角度它會看起來閃閃發亮呢。' },
    { en: 'Helen loves to listen to music.', zh: 'Helen 喜歡聽音樂。' },
    { en: "Her favorite song is 'The birds that flew.' Her music brings joy to our ears.", zh: '她最喜歡的歌是 The birds that flew。這首歌聽起來十分悅耳。' },
    { en: 'We have a beautiful garden.', zh: '我家有座很漂亮的花園。' },
    { en: 'I will show them the pretty flowers and the funny looking bugs.', zh: '我會帶他們去看美麗的花和長相有趣的蟲子。' },
    { en: 'We are all a good fit.', zh: '我跟我的朋友們是最佳團隊！' },
    { en: "Come on friends, let's have some fun!", zh: '來吧，朋友們！一起來玩吧！' },
    // Helen's Walk (15)
    { en: 'Helen went for a walk with her friend one sunny morning.', zh: 'Helen 在一個晴朗的早晨和她的朋友去散步。' },
    { en: 'She used all five senses to enjoy the world around her.', zh: '她用五種感官來感受周圍的世界。' },
    { en: 'First, she used her eyes to see the bright blue sky.', zh: '首先，她用眼睛看見了明亮的藍天。' },
    { en: 'She saw four birds fly from the big tree.', zh: '她看見四隻鳥從大樹上飛走。' },
    { en: 'The birds that flew past made her feel amazed.', zh: '飛過的鳥兒讓她感到驚嘆。' },
    { en: 'Then she used her ears to hear the birds sing.', zh: '接著她用耳朵聆聽鳥兒的歌聲。' },
    { en: 'The singing was so beautiful and fun to listen to.', zh: '歌聲非常美妙，聽起來很有趣。' },
    { en: 'Next, she used her nose to smell the flowers by the path.', zh: '接下來，她用鼻子聞路旁的花朵。' },
    { en: 'The flower smelled sweet and made her feel peaceful.', zh: '花朵聞起來香甜，讓她感到平靜。' },
    { en: 'She used her hands to touch the soft green leaves.', zh: '她用雙手觸摸柔軟的綠葉。' },
    { en: 'The leaves felt smooth and cool.', zh: '葉子摸起來光滑又涼爽。' },
    { en: 'Finally, she used her tongue to taste a red berry from a bush.', zh: '最後，她用舌頭嚐了一顆從灌木叢摘下的紅莓。' },
    { en: 'It was sweet and a little funny tasting.', zh: '味道甜甜的，還有點奇妙。' },
    { en: 'Helen felt so grateful for her five senses.', zh: 'Helen 對自己的五種感官感到非常感激。' },
    { en: 'She said, "Every day is a gift — for those who know how to see."', zh: '她說：「每一天都是禮物——對那些懂得用心看的人來說。」' },
    // Sentence Patterns (5)
    { en: 'I see with my eyes.', zh: '我用眼睛看。' },
    { en: 'I hear with my ears.', zh: '我用耳朵聽。' },
    { en: 'I smell with my nose.', zh: '我用鼻子聞。' },
    { en: 'I touch with my hands.', zh: '我用手觸摸。' },
    { en: 'I taste with my tongue.', zh: '我用舌頭嚐。' },
    // You Are My Sunshine (8)
    { en: 'You are my sunshine, my only sunshine.', zh: '你是我的陽光，我唯一的陽光。' },
    { en: 'You make me happy when skies are grey.', zh: '當天空陰沉時，你讓我快樂。' },
    { en: 'You\'ll never know, dear, how much I love you.', zh: '親愛的，你永遠不知道我有多愛你。' },
    { en: 'Please don\'t take my sunshine away.', zh: '請不要帶走我的陽光。' },
    { en: 'The other night, dear, as I lay sleeping.', zh: '親愛的，某天晚上，當我躺著睡覺時。' },
    { en: 'I dreamed I held you in my arms.', zh: '我夢見把你抱在懷裡。' },
    { en: 'When I awoke, dear, I was mistaken.', zh: '當我醒來，親愛的，我發現那只是夢。' },
    { en: 'And I hung my head and cried.', zh: '於是我低下頭哭了起來。' },
  ],

  weeklyQuote: { en: 'Every day is a gift — for those who know how to see.', emoji: '👁️' },
  weeklySong: { title: 'You Are My Sunshine', line: 'You make me happy when skies are grey.' },

  dialogues: [],
};
